### ISSUE TITLE
How to compile the source code to a dll file

### ISSUE THREAD

**Issue by leoyong** [thenickdude/InnoCallback#1]
hello,I open the InnoCallback.dproj with delphi 2007 and it said “cannot find resource file”.and when I compile the project with ”ctrl + F9“, I cannot find a "InnoCallback.dll" file created.

Could you please tell me how to compile the source code ? 

Thank you very much~

**Comment by thenickdude** [comment]
Normally the .res file gets recreated when the project is opened, I've removed references to it instead because it isn't actually needed for this DLL. Please try out the new commit.

**Comment by leoyong** [comment]
the new commit works well,Thank you very much~!

**Comment by thenickdude** [comment]
Great!
